pull_request_rules:
  - name: Automatic update to the main branch for pull requests
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # skip GH draft PRs
      - author=MarcoIeni # don't update PRs from users
    actions:
      update:
